version: "2"
services:
  app:
    restart: always
    build: .
    command: node server.js
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27019:27017"